### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [filthyharold/LegoPicGenerator#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by suprafun** [comment]
Hello, sorry to bother you. Just wanted to bump this. Thanks.

**Comment by dankar89** [comment]
@suprafun I've added a license.
Go ahead and do whatever you want with the code ;)

**Comment by suprafun** [comment]
Thank you so VERY VERY MUCH :smiley:
